// <auto-generated>
// Rewired Constants
// This list was generated on 1/31/2022 12:33:07 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move")]
        public const int Move = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Turn")]
        public const int Turn = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Slap")]
        public const int Slap = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "SelfDestruct")]
        public const int SelfDestruct = 3;
        // Menu
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "Action0")]
        public const int UIHorizontal = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "UIVertical")]
        public const int UIVertical = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "UISubmit")]
        public const int UISubmit = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Menu", friendlyName = "UICancel")]
        public const int UICancel = 7;
    }
}
